# Generated by Django 5.0.14 on 2025-05-27 03:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ProductionDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ProductionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('plant_loc', models.CharField(choices=[('PULILAN', 'Pulilan'), ('TARLAC', 'Tarlac')], max_length=50)),
                ('shift', models.CharField(choices=[('DAY SHIFT', 'Day Shift'), ('NIGHT SHIFT', 'Night Shift')], max_length=20)),
                ('time_start', models.TimeField()),
                ('time_end', models.TimeField()),
                ('total', models.CharField(max_length=50)),
                ('boiler_temp', models.DecimalField(decimal_places=2, max_digits=5)),
                ('cooking_oil_temp', models.DecimalField(decimal_places=2, max_digits=5)),
                ('output_temp', models.DecimalField(decimal_places=2, max_digits=5)),
                ('input_temp', models.DecimalField(decimal_places=2, max_digits=5)),
                ('formatic_stroke_min', models.DecimalField(decimal_places=2, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('prod_min_descrip', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='WMSApp.productiondescription')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='WMSApp.product')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='WMSApp.source')),
            ],
            options={
                'ordering': ['-date', '-time_start'],
            },
        ),
    ]
