# Generated by Django 5.0.14 on 2025-05-28 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WMSApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionrecord',
            name='monthyear',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='productionrecord',
            name='section',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterModelTable(
            name='productionrecord',
            table='productionrecord',
        ),
    ]
