# Generated by Django 5.0.14 on 2025-05-28 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WMSApp', '0002_productionrecord_monthyear_productionrecord_section_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productionrecord',
            name='plant_loc',
            field=models.CharField(choices=[('PULILAN', 'Pulilan'), ('TARLAC', 'Tarlac')], max_length=255),
        ),
        migrations.AlterField(
            model_name='productionrecord',
            name='prod_min_descrip',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='productionrecord',
            name='product',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='productionrecord',
            name='shift',
            field=models.CharField(choices=[('DAY SHIFT', 'Day Shift'), ('NIGHT SHIFT', 'Night Shift')], max_length=255),
        ),
        migrations.AlterField(
            model_name='productionrecord',
            name='source',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='productionrecord',
            name='time_end',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='productionrecord',
            name='time_start',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='productionrecord',
            name='total',
            field=models.CharField(max_length=100),
        ),
    ]
