# Generated by Django 5.0.14 on 2025-05-28 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WMSApp', '0003_alter_productionrecord_plant_loc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productionrecord',
            name='date',
            field=models.CharField(max_length=255),
        ),
    ]
