# Generated by Django 5.0.14 on 2025-05-28 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WMSApp', '0004_alter_productionrecord_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productionrecord',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='productionrecord',
            name='updated_at',
        ),
    ]
