# Generated by Django 5.0.14 on 2025-05-28 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WMSApp', '0006_productionrecord_meters_per_min'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productionrecord',
            name='plant_loc',
            field=models.CharField(choices=[('PULILAN', 'Pulilan'), ('TARLAC', 'Tarlac')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='productionrecord',
            name='shift',
            field=models.CharField(choices=[('DAY SHIFT', 'Day Shift'), ('NIGHT SHIFT', 'Night Shift')], max_length=255, null=True),
        ),
    ]
