# Generated by Django 5.0.14 on 2025-05-28 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WMSApp', '0007_alter_productionrecord_plant_loc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productionrecord',
            name='source',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
