# Generated by Django 5.0.14 on 2025-05-28 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WMSApp', '0008_alter_productionrecord_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productionrecord',
            name='prod_min_descrip',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
