# Generated by Django 5.0.14 on 2025-05-28 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WMSApp', '0009_alter_productionrecord_prod_min_descrip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productionrecord',
            name='boiler_temp',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='productionrecord',
            name='formatic_stroke_min',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='productionrecord',
            name='meters_per_min',
            field=models.IntegerField(null=True),
        ),
    ]
