# Generated by Django 5.0.14 on 2025-05-31 05:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WMSApp', '0010_alter_productionrecord_boiler_temp_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'ProductData',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SourceData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Source', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'SourceData',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VAPProductionData',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('Date', models.DateField(db_column='Date')),
                ('PlantLoc', models.CharField(choices=[('PULILAN', 'Pulilan'), ('TARLAC', 'Tarlac')], db_column='PlantLoc', max_length=255, null=True)),
                ('Shift', models.CharField(choices=[('DAY SHIFT', 'Day Shift'), ('NIGHT SHIFT', 'Night Shift')], db_column='Shift', max_length=255, null=True)),
                ('TimeStart', models.TimeField(db_column='TimeStart')),
                ('TimeEnd', models.TimeField(db_column='TimeEnd')),
                ('Total', models.CharField(db_column='Total', max_length=100)),
                ('BoilerTemp', models.IntegerField(db_column='BoilerTemp')),
                ('CookingOilTemp', models.DecimalField(db_column='CookingOilTemp', decimal_places=2, max_digits=5)),
                ('MetersPerMin', models.IntegerField(db_column='MetersPerMin', null=True)),
                ('OutputTemp', models.DecimalField(db_column='OutputTemp', decimal_places=2, max_digits=5)),
                ('InputTemp', models.DecimalField(db_column='InputTemp', decimal_places=2, max_digits=5)),
                ('FormaticStrokeMin', models.IntegerField(db_column='FormaticStrokeMin')),
                ('Section', models.CharField(db_column='Section', max_length=255, null=True)),
                ('MonthYear', models.CharField(db_column='MonthYear', max_length=255, null=True)),
            ],
            options={
                'db_table': 'VAPProductionData',
                'ordering': ['-Date', '-TimeStart'],
            },
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='ProductionRecord',
        ),
        migrations.DeleteModel(
            name='Source',
        ),
        migrations.AlterModelOptions(
            name='productiondescription',
            options={'managed': False},
        ),
        migrations.AddField(
            model_name='vapproductiondata',
            name='ProdMinDescrip',
            field=models.ForeignKey(blank=True, db_column='ProdMinDescrip', null=True, on_delete=django.db.models.deletion.SET_NULL, to='WMSApp.productiondescription'),
        ),
        migrations.AddField(
            model_name='vapproductiondata',
            name='Product',
            field=models.ForeignKey(blank=True, db_column='Product', null=True, on_delete=django.db.models.deletion.SET_NULL, to='WMSApp.productdata'),
        ),
        migrations.AddField(
            model_name='vapproductiondata',
            name='Source',
            field=models.ForeignKey(blank=True, db_column='Source', null=True, on_delete=django.db.models.deletion.SET_NULL, to='WMSApp.sourcedata'),
        ),
    ]
