# Generated by Django 5.0.14 on 2025-06-02 17:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WMSApp', '0011_productdata_sourcedata_vapproductiondata_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vapproductiondata',
            name='ProdMinDescrip',
            field=models.ForeignKey(db_column='ProdMinDescrip', null=True, on_delete=django.db.models.deletion.SET_NULL, to='WMSApp.productiondescription'),
        ),
        migrations.AlterField(
            model_name='vapproductiondata',
            name='Product',
            field=models.ForeignKey(db_column='Product', null=True, on_delete=django.db.models.deletion.SET_NULL, to='WMSApp.productdata'),
        ),
        migrations.AlterField(
            model_name='vapproductiondata',
            name='Source',
            field=models.ForeignKey(db_column='Source', null=True, on_delete=django.db.models.deletion.SET_NULL, to='WMSApp.sourcedata'),
        ),
        migrations.AlterModelTable(
            name='productiondescription',
            table='Production_Description',
        ),
    ]
